In [1]:
from synthetic import Synthetic
import torch
import numpy as np
np.random.seed(42)

In [2]:
dataset = Synthetic(num_examples=100, mode='mu')

In [3]:
dataset.inputs.shape

torch.Size([2400, 2])

In [4]:
dataset.inputs.shape

torch.Size([2400, 2])

In [5]:
dataset.targets.shape

torch.Size([2400])

In [6]:
dataset.mu0.shape

(2400,)

In [7]:
len(dataset.x)

2400

In [8]:
indices = np.arange(len(dataset.x))
# Shuffle the indices in-place
np.random.shuffle(indices)

In [9]:
print(indices)

[ 394 1566  865 ...  924  944 1654]


In [10]:
dataset.t

array([1., 1., 0., ..., 0., 1., 0.], dtype=float32)

In [11]:
dataset.mu0.shape

(2400,)

In [12]:
dataset.t.shape

(2400,)

In [14]:
from ihdp import IHDP
from pathlib import Path

In [27]:
ihdp_test = IHDP(root='assets', split='test', mode='mu', seed=42)

In [28]:
ihdp_test.x

array([[ 0.20864718, -0.20308192,  0.38408515, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.0955026 ,  1.7970777 , -1.1063647 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.42495337,  0.5969819 , -0.73375225, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.46821463,  0.9970138 ,  0.7566976 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.8246312 , -2.2032416 ,  0.7566976 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.51147586, -0.20308192, -0.73375225, ...,  0.        ,
         0.        ,  1.        ]], dtype=float32)

In [29]:
ihdp_train = IHDP(root='assets', split='train', mode='mu', seed=42)

In [30]:
ihdp_train.x

array([[-0.33211833,  0.5969819 , -0.3611398 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.9327843 , -2.2032416 ,  2.2471476 , ...,  0.        ,
         1.        ,  0.        ],
       [-0.5700552 , -0.20308192, -0.3611398 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.3550701 ,  1.3970457 , -0.3611398 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.1820251 ,  1.3970457 , -0.73375225, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.8791964 ,  1.3970457 , -0.3611398 , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)

In [31]:
ihdp_valid = IHDP(root='assets', split='valid', mode='mu', seed=42)
ihdp_valid.x

array([[ 0.63260734,  0.9970138 , -0.3611398 , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.27353904,  0.19694999, -0.3611398 , ...,  0.        ,
         0.        ,  0.        ],
       [-2.2572436 , -1.4031776 ,  1.5019226 , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.8462617 , -1.8032095 ,  2.61976   , ...,  0.        ,
         0.        ,  0.        ],
       [-0.98103696, -0.20308192,  0.7566976 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.20233463,  1.3970457 , -0.73375225, ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)